### PR TITLE
44980 : iOS_US_Notification: Display badge on application

### PR DESCRIPTION
**Pull request by wbenabdessalem**
TO TEST

Given i am a user mobile
When i receive a x number of notification
Then a bagde notification appears of x number notification

### CODE REVIEW

**Review by ahamdi — CHANGES_REQUESTED** [review]
Please remove unneeded print instructions

**Comment by wbenabdessalem** [comment]
> Please remove unneeded print instructions

@ahamdi  d'accord

**Comment by wbenabdessalem** [comment]
@ahamdi branch doit etre annulé.

**Comment by plamarque** [comment]
@wbenabdessalem  use english only please. thanks

**Comment by wbenabdessalem** [comment]
> @wbenabdessalem  use english only please. thanks 

@plamarque  ok, :)

**Pull request closed without merging**
