### PR TITLE
Task-60976: [Mobile][ECTI-152][IOS] PDF document preview; App crash

### PR DESCRIPTION
**Pull request by wbenabdessalem**
IOS 16.1.1
Previewing a pdf document crashes the exo mobile app, it becomes unusable.

Fix : Update Pods and Excluded Architectures with xCode 14.2

### CODE REVIEW

**Review by ahamdi — COMMENTED** [review]
Will the application run with older iOS versions ? with which versions will it be incompatible after this change ? what will be the minimum version of iOS ?

**Comment by ahamdi** [comment]
@wbenabdessalem besides the CI build of this PR is still using ios 15

**Comment by wbenabdessalem** [comment]
> @wbenabdessalem besides the CI build of this PR is still using ios 15

Actually after update, the build was uploaded using the iOS 16.2, xCode 14.2, and macOS 13.0
Note: we should also update the CI build.

**Comment by ahamdi** [comment]
@wbenabdessalem the build is stilll failing because the profile of share-extension si not correct
besides, my question is about what minimum version will the application support now ? Could you do tests so we can understand ?

**Pull request closed without merging**
